-- ============================================================
-- PSP Project Database — PostgreSQL 16
-- Dikonversi dari MySQL (nsi_project -> psp_project).
-- Perbedaan utama vs versi MySQL:
--   - AUTO_INCREMENT        -> GENERATED BY DEFAULT AS IDENTITY
--   - ENUM('a','b','c')     -> VARCHAR + CHECK constraint
--   - ENGINE=InnoDB/backtick-> sintaks PostgreSQL standar
--   - current_timestamp()   -> CURRENT_TIMESTAMP
-- ============================================================

-- --------------------------------------------------------
-- Table: categories
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name VARCHAR(100) NOT NULL
);

INSERT INTO categories (id, category_name) VALUES
(1, 'Makanan'),
(2, 'Minuman'),
(3, 'Elektronik'),
(4, 'Furnitur'),
(6, 'Fashion')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------
-- Table: items
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
  item_name VARCHAR(150) NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  image_path VARCHAR(255) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL
);

INSERT INTO items (id, category_id, item_name, price, stock, image_path, image) VALUES
(3, 4, 'Yamaha Desk', 600000.00, 15, NULL, '1776926550_yamahadesk.png'),
(4, 6, 'Sandal Gaya Cantik Perempuan', 24000.00, 95, NULL, '1776934449_sandal.png'),
(5, 1, 'Basreng 100 gram', 5690.00, 40, NULL, '1776934547_basreng.png'),
(6, 4, 'Speaker Sound Horeg', 3799000.00, 3, NULL, '1776934622_speaker.png'),
(7, 6, 'Sepatu Pria', 47000.00, 24, NULL, '1776934854_sepatu.png'),
(8, 6, 'Parfum Extrait de Perfume', 30000.00, 46, NULL, '1776934878_parfum.png')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------
-- Table: users
-- role: CHECK constraint pengganti ENUM MySQL
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'customer'
    CHECK (role IN ('admin', 'pegawai', 'customer')),
  profile_photo VARCHAR(255) DEFAULT NULL
);

-- Password: admin123, gab123, pegawai123 (hash bcrypt dari password_hash() PHP)
INSERT INTO users (id, username, password, role) VALUES
(1, 'admin',    '$2y$10$DG3u86ykugwSddfix5i/k.xjpxkV86UMiGD6.CU5f/xkEma8BmoTS', 'admin'),
(2, 'gabrielle','$2y$10$6LdwHvVNSa2lWkyXU7bX2OB4GYdWuJpwedvVJNRZZy16jJ916KHOe', 'customer'),
(3, 'pegawai1', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'pegawai')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------
-- Table: orders (Purchase Order)
-- status: pending -> approved -> completed, atau pending -> rejected
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES items (id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL,
  total_price NUMERIC(10,2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'completed')),
  order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------------------
-- Table: transactions
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS transactions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users (id),
  item_id INTEGER REFERENCES items (id),
  quantity INTEGER DEFAULT NULL,
  total_price NUMERIC(10,2) DEFAULT NULL,
  transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO transactions (id, user_id, item_id, quantity, total_price, transaction_date) VALUES
(1, NULL, 3, 4, 2400000.00, '2026-04-23 06:49:02'),
(2, 2, 3, 4, 2400000.00, '2026-04-23 07:17:00'),
(3, 2, 3, 1, 600000.00, '2026-04-23 07:17:02'),
(4, 2, 3, 13, 7800000.00, '2026-04-23 07:17:05'),
(5, 2, 3, 3, 1800000.00, '2026-04-23 08:05:42'),
(6, 2, 5, 10, 56900.00, '2026-04-23 08:57:33'),
(7, 2, 4, 5, 120000.00, '2026-04-23 08:57:37'),
(8, 2, 6, 2, 7598000.00, '2026-04-23 08:57:40'),
(9, 2, 7, 1, 47000.00, '2026-04-23 09:01:30'),
(10, 2, 8, 4, 120000.00, '2026-04-23 09:01:33')
ON CONFLICT (id) DO NOTHING;

-- --------------------------------------------------------
-- Table: activity_logs
-- OWASP A09 - Security Logging and Alerting Failures.
-- TIDAK PERNAH menyimpan password/token.
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS activity_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  event_type VARCHAR(50) NOT NULL,
  description TEXT DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activity_logs_event ON activity_logs (event_type);
CREATE INDEX IF NOT EXISTS idx_activity_logs_created ON activity_logs (created_at);

-- Sinkronkan sequence IDENTITY setelah INSERT dengan id eksplisit
SELECT setval(pg_get_serial_sequence('categories', 'id'), (SELECT MAX(id) FROM categories));
SELECT setval(pg_get_serial_sequence('items', 'id'), (SELECT MAX(id) FROM items));
SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('transactions', 'id'), (SELECT MAX(id) FROM transactions));
